'use strict'

// Facebook actions
export const FB_LOGIN = 'FB_LOGIN'
export const FB_LOGOUT = 'FB_LOGOUT'
export const FB_FETCH_PROFILE = 'FB_FETCH_PROFILE'
export const FB_REFRESH_PROFILE = 'FB_REFRESH_PROFILE'
export const FB_FETCH_EVENTS = 'FB_FETCH_EVENTS'
export const FB_REFRESH_EVENTS = 'FB_REFRESH_EVENTS'
export const FB_FETCH_USERS_ATTENDING_EVENT = 'FB_FETCH_USERS_ATTENDING_EVENT'
export const FB_REFRESH_USERS_ATTENDING_EVENT = 'FB_REFRESH_USERS_ATTENDING_EVENT'

// Navigation actions
export const NAVIGATE_TO = 'NAVIGATE_TO'
export const NAVIGATE_BACK = 'NAVIGATE_BACK'
export const CLEAR_HISTORY = 'CLEAR_HISTORY'

// Event Actions
export const UPDATE_EVENT_ETA = 'UPDATE_EVENT_ETA'
