'use strict'

// Event actions
export const FETCH_FB_EVENTS = 'FETCH_FB_EVENTS'
export const REFRESH_FB_EVENTS = 'REFRESH_FB_EVENTS'
export const FETCH_USERS_ATTENDING_FB_EVENT = 'FETCH_USERS_ATTENDING_FB_EVENT'
export const REFRESH_USERS_ATTENDING_FB_EVENT = 'REFRESH_USERS_ATTENDING_FB_EVENT'
export const UPDATE_EVENT_ETA = 'UPDATE_EVENT_ETA'
export const CHECK_IN_EVENT = 'CHECK_IN_EVENT'
export const WAIT_FOR_EVENT_ETAS = 'WAIT_FOR_EVENT_ETAS'
export const REFRESH_EVENT_ETAS = 'REFRESH_EVENT_ETAS'

// Login actions
export const FB_LOGIN = 'FB_LOGIN'
export const FB_LOGOUT = 'FB_LOGOUT'

// Navigation actions
export const NAVIGATE_TO = 'NAVIGATE_TO'
export const NAVIGATE_BACK = 'NAVIGATE_BACK'
export const CLEAR_HISTORY = 'CLEAR_HISTORY'

// Profile actions
export const FETCH_FB_PROFILE = 'FETCH_FB_PROFILE'
export const REFRESH_FB_PROFILE = 'REFRESH_FB_PROFILE'